name: Benchmark Pull Request

on:
  pull_request_target:
    branches:
      - master

permissions:
  pull-requests: write

jobs:
  benchmark:
    name: "Benchmarks"
    uses: "SciML/.github/.github/workflows/benchmark.yml@v1"
    with:
      julia-version: "1.11"
    secrets: "inherit"
