name: "CI (BoundaryValueDiffEq)"

on:
  pull_request:
    branches:
      - master
    paths:
      - "src/**"
      - "ext/**"
      - "test/**"
      - "Project.toml"
      - ".github/workflows/CI_BoundaryValueDiffEq.yml"
      - "lib/BoundaryValueDiffEqCore/**"
      - "lib/BoundaryValueDiffEqMIRK/**"
      - "lib/BoundaryValueDiffEqMIRKN/**"
      - "lib/BoundaryValueDiffEqFIRK/**"
      - "lib/BoundaryValueDiffEqShooting/**"
      - "lib/BoundaryValueDiffEqAscher/**"
  push:
    branches:
      - master

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

env:
  RETESTITEMS_NWORKERS: 4
  RETESTITEMS_NWORKER_THREADS: 2

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1"
          - "lts"
          - "pre"
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: "Install Dependencies and Run Tests"
        run: |
          import Pkg
          Pkg.Registry.update()
          # Install packages present in subdirectories
          dev_pks = Pkg.PackageSpec[]
          for path in ("lib/BoundaryValueDiffEqCore", "lib/BoundaryValueDiffEqMIRK", "lib/BoundaryValueDiffEqMIRKN", "lib/BoundaryValueDiffEqFIRK", "lib/BoundaryValueDiffEqShooting", "lib/BoundaryValueDiffEqAscher")
              push!(dev_pks, Pkg.PackageSpec(; path))
          end
          Pkg.develop(dev_pks)
          Pkg.instantiate()
          Pkg.test(; coverage="user")
        shell: julia --color=yes --code-coverage=user --depwarn=yes --project=. {0}
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src,ext,lib/BoundaryValueDiffEqCore/src,lib/BoundaryValueDiffEqMIRK/src,lib/BoundaryValueDiffEqMIRKN/src,lib/BoundaryValueDiffEqFIRK/src,lib/BoundaryValueDiffEqShooting/src,lib/BoundaryValueDiffEqAscher/src
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          fail_ci_if_error: false

  downgrade:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.10"
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-downgrade-compat@v1
        with:
          skip: BoundaryValueDiffEqCore, BoundaryValueDiffEqMIRK, BoundaryValueDiffEqMIRKN, BoundaryValueDiffEqFIRK, BoundaryValueDiffEqShooting, BoundaryValueDiffEqAscher
      - name: "Install Dependencies and Run Tests"
        run: |
          import Pkg
          Pkg.Registry.update()
          # Install packages present in subdirectories
          dev_pks = Pkg.PackageSpec[]
          for path in ("lib/BoundaryValueDiffEqCore", "lib/BoundaryValueDiffEqMIRK", "lib/BoundaryValueDiffEqMIRKN", "lib/BoundaryValueDiffEqFIRK", "lib/BoundaryValueDiffEqShooting", "lib/BoundaryValueDiffEqAscher")
              push!(dev_pks, Pkg.PackageSpec(; path))
          end
          Pkg.develop(dev_pks)
          Pkg.instantiate()
          Pkg.test(; coverage="user")
        shell: julia --color=yes --code-coverage=user --depwarn=yes --project=. {0}
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src,ext,lib/BoundaryValueDiffEqCore/src,lib/BoundaryValueDiffEqMIRK/src,lib/BoundaryValueDiffEqMIRKN/src,lib/BoundaryValueDiffEqFIRK/src,lib/BoundaryValueDiffEqShooting/src,lib/BoundaryValueDiffEqAscher/src
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          fail_ci_if_error: false
